### PR TITLE
Use shutil.which to find redis-server

### LINKED ISSUE #374: Find redis-server binary in other locations than /usr/bin
### What action do you want to perform

Use `shutil.which` to detect the location of the `redis-server` binary instead of using the currently hard-coded "/usr/bin/redis-server".

Maybe with a fallback to "/usr/bin/redis-server" if `which` doesn't find anything.

Something like:

    [...]
    from shutil import which
    [...]
    parser.addini(
        name="redis_exec",
        help=_help_exec, 
        default=which("redis-server") or "/usr/bin/redis-server"
    )

### What are the expected results

### PR DESCRIPTION
**Pull request by sc68cal**
This fixes #374

### CODE REVIEW

**Review by fizyk — APPROVED** [review]

**Comment by ayyoubelamrani4** [comment]
@fizyk this is not released yet, right?

**Comment by fizyk** [comment]
Sorry, not yet, digging through the backlog currently, and the change to make dependabot's PRs treated as third party PRs hadn't helped with it.

**Comment by ayyoubelamrani4** [comment]
@fizyk 
Alright, thanks for the update 🙏🏼
out of scope; can we let the fixture connect through also through a port and hostname? 
Use-case is using pytest-redis withing a github action CI where the redis instance is accessible only through the port.

**Comment by fizyk** [comment]
@ayyoubelamrani4 I suppose 🤔

**Pull request merged**
